ci: use `cargo fmt` instead of direct `rustfmt` call
Reference: #85

Signed-off-by: Renato Westphal <renato@opensourcerouting.org>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -19,8 +19,8 @@ jobs:
       - uses: Swatinem/rust-cache@v2
       - name: "rustfmt --check"
         run: |
-          if ! rustfmt --check --edition 2024 $(git ls-files '*.rs'); then
-            printf "Please run \`rustfmt --edition 2024 \$(git ls-files '*.rs')\` to fix rustfmt errors.\nSee CONTRIBUTING.md for more details.\n" >&2
+          if ! cargo fmt --all --check; then
+            printf "Please run \`cargo fmt --all\` locally to fix formatting errors.\nSee CONTRIBUTING.md for more details.\n" >&2
             exit 1
           fi
 
