all: use custom formatting in northbound modules
rustfmt has a long-standing issue where formatting does not occur
in the presence of very long lines.

Holo makes heavy use of YANG code generation, and some generated
YANG module paths can be quite long due to the IETF YANG data
hierarchy. As a result, rustfmt was failing to format portions of
the northbound code.

This change sets rustfmt max_width to 240, but only for the
northbound modules across all workspace crates. This ensures that
northbound code is consistently formatted without affecting the
rest of the codebase.

In the long term, once the rustfmt issue is resolved, we can revert
to a single, consolidated rustfmt configuration.

[1] https://github.com/rust-lang/rustfmt/issues/3863

Signed-off-by: Renato Westphal <renato@opensourcerouting.org>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -19,8 +19,8 @@ jobs:
       - uses: Swatinem/rust-cache@v2
       - name: "rustfmt --check"
         run: |
-          if ! cargo fmt --all --check; then
-            printf "Please run \`cargo fmt --all\` locally to fix formatting errors.\nSee CONTRIBUTING.md for more details.\n" >&2
+          if ! rustfmt --check $(git ls-files '*.rs'); then
+            printf "Please run \`rustfmt \$(git ls-files '*.rs')\` locally to fix formatting errors.\nSee CONTRIBUTING.md for more details.\n" >&2
             exit 1
           fi
 
