ci: add PR code formatting check
Add a CI pipeline to validate code formatting on Pull Requests.

Also, temporarily disable "wrap_comments = true" in rustfmt.toml until a
rustfmt regression [1] is fixed.

[1] https://github.com/rust-lang/rustfmt/issues/5862

Signed-off-by: Renato Westphal <renato@opensourcerouting.org>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,17 +1,29 @@
 name: CI
 
-on:
-  push:
-    branches: [ master ]
-  pull_request:
-    branches: [ master ]
+on: [push, pull_request]
 
 env:
   CARGO_TERM_COLOR: always
 
 jobs:
+  fmt:
+    name: Code Formatting Check
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: dtolnay/rust-toolchain@nightly
+        with:
+          components: rustfmt
+      - uses: Swatinem/rust-cache@v2
+      - name: "rustfmt --check"
+        run: |
+          if ! rustfmt --check --edition 2021 $(git ls-files '*.rs'); then
+            printf "Please run \`rustfmt --edition 2021 \$(git ls-files '*.rs')\` to fix rustfmt errors.\nSee CONTRIBUTING.md for more details.\n" >&2
+            exit 1
+          fi
+
   test:
-    name: Test
+    name: Tests and Coverage Report
     env:
       holo: rust_ci_github_actions_workflow
       CARGO_INCREMENTAL: 0
@@ -41,7 +53,8 @@ jobs:
           files: ./lcov.info
           fail_ci_if_error: true
 
-  push-store-image:
+  push-image:
+    name: Docker Image Build
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
